// var x=100;
// var x=200;
// console.log(x);
// let z=100;
// let z=200;
// console.log(z);
let arr=["Sanju","Abi","Jungkook"];
arr.unshift("Keen");
console.log(arr);
arr.push("V");
console.log(arr);
arr.pop();
console.log(arr);
arr.shift();
console.log(arr);
arr.splice(1,1,"Tian Xu");
console.log(arr);
arr.splice(1,2);
console.log(arr);
arr.unshift("Keen","V");
console.log(arr);
arr.push("Jimin","RM");
console.log(arr);
let newArr=arr.slice(0,2);
console.log(newArr);